version: 3

tasks:
  zip:
    cmds:
      - cmd: pip3 install cachetools --target .\rusticators\vpc\
        platforms: [windows]
      - cmd: pwsh.exe -command "Compress-Archive .\rusticators\vpc\* -DestinationPath .\temp\vpc.zip -Force"
        platforms: [windows]

  security:
    cmd: poetry run bandit -r ./rusticators/vpc

  mypy:
    cmd: poetry run mypy --pretty ./rusticators/vpc

  format:
    cmds:
      - cmd: poetry run ruff format ./rusticators/vpc

  lint:
    deps: [format]
    cmds:
      - poetry run ruff check ./rusticators/vpc

  prerelease:
    cmds:
      - task: lint
      - task: security
      - task: mypy

  build_container:
    vars:
      ECR_REPO: '{{.ECR_REPO}}'
      ACCOUNT_ID: '{{.ACCOUNT_ID}}'
      REGION: '{{default "us-east-2" .REGION}}'
      COMMIT_ID:
        sh: git rev-parse --short=11 HEAD
    cmds:
      - docker build -t rusticators-vpc -f ./Dockerfile.aws .
      - docker tag rusticators-vpc:latest {{.ACCOUNT_ID}}.dkr.ecr.{{.REGION}}.amazonaws.com/{{.ECR_REPO}}:latest
      - docker tag rusticators-vpc:latest {{.ACCOUNT_ID}}.dkr.ecr.{{.REGION}}.amazonaws.com/{{.ECR_REPO}}:{{.COMMIT_ID}}
      - docker push {{.ACCOUNT_ID}}.dkr.ecr.{{.REGION}}.amazonaws.com/{{.ECR_REPO}}:{{.COMMIT_ID}}

  containertest:
    cmds:
      - task: build_container
        vars: { ECR_REPO: 'test-rusticators-vpc', ACCOUNT_ID: '547201116507' }

  deploy:
    deps: [zip]
    cmds:
      - cmd: pulumi up