FROM public.ecr.aws/lambda/python:3.11

COPY requirements.txt ./requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt --target ${LAMBDA_TASK_ROOT}

COPY ../rusticators/vpc ${LAMBDA_TASK_ROOT}

CMD ["lambda_function.lambda_handler"]